const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const iconSizes = {
  // Windows
  'icon.ico': [16, 24, 32, 48, 64, 128, 256],
  // macOS
  'icon.icns': [16, 32, 64, 128, 256, 512, 1024],
  // Linux
  'icon.png': [512],
  // Additional PNG sizes
  'icon-16x16.png': [16],
  'icon-32x32.png': [32],
  'icon-48x48.png': [48],
  'icon-64x64.png': [64],
  'icon-128x128.png': [128],
  'icon-256x256.png': [256],
  'icon-512x512.png': [512],
  'icon-1024x1024.png': [1024]
};

async function generateIcons() {
  const svgPath = path.join(__dirname, '../public/icons/icon.svg');
  const outputDir = path.join(__dirname, '../public/icons');
  
  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  console.log('Generating icons from SVG...');

  // Generate PNG files for different sizes
  for (const [filename, sizes] of Object.entries(iconSizes)) {
    if (filename.endsWith('.png')) {
      const size = sizes[0];
      const outputPath = path.join(outputDir, filename);
      
      try {
        await sharp(svgPath)
          .resize(size, size)
          .png()
          .toFile(outputPath);
        
        console.log(`✓ Generated ${filename} (${size}x${size})`);
      } catch (error) {
        console.error(`✗ Failed to generate ${filename}:`, error.message);
      }
    }
  }

  // For ICO and ICNS, we'll create the largest PNG and let electron-builder handle conversion
  try {
    // Generate a high-res PNG for ICO conversion
    await sharp(svgPath)
      .resize(256, 256)
      .png()
      .toFile(path.join(outputDir, 'icon-for-ico.png'));
    
    console.log('✓ Generated icon-for-ico.png (256x256)');

    // Generate a high-res PNG for ICNS conversion
    await sharp(svgPath)
      .resize(1024, 1024)
      .png()
      .toFile(path.join(outputDir, 'icon-for-icns.png'));
    
    console.log('✓ Generated icon-for-icns.png (1024x1024)');
  } catch (error) {
    console.error('✗ Failed to generate conversion PNGs:', error.message);
  }

  console.log('\n🎉 Icon generation completed!');
  console.log('Note: ICO and ICNS files will be generated by electron-builder during build process.');
}

generateIcons().catch(console.error);